@echo off
echo Mengaktifkan port forwarding untuk HP fisik...
"C:\Users\NABIL\AppData\Local\Android\Sdk\platform-tools\adb.exe" reverse tcp:5000 tcp:5000
echo Menjalankan aplikasi Flutter...
flutter run
